### ISSUE TITLE
Change Font File Name

### ISSUE THREAD

**Issue by Samadhan-Medge** [Livin21/DroidAwesome#1] opened 2017-01-03 11:34 UTC
I'm not able to change font file name. No provision is available to set font file name rather than 'font-awesome.ttf'.

**Comment by Livin21** [comment] 2017-01-03 15:07
Can you explain the issue with a use case?

**Comment by Samadhan-Medge** [comment] 2017-01-04 08:33
I have added font file 'my-font.ttf' under assets/fonts folder at this situation when I'm going to set drawable to TextView or ImageView then its not showing icon, when I change 'my-font.ttf' to 'font-awesome.ttf' its showing icons perfectly. So my concern is I want to keep font file name as I required.

**Comment by Livin21** [comment] 2017-01-04 09:10
Okay. Thanks. I've added a function for specifying file name. Will release the library with the change soon.

**Comment by Samadhan-Medge** [comment] 2017-01-04 13:12
Thanks Livin21 :+1:

**Comment by Livin21** [comment] 2017-01-05 12:10
@Samadhan-Medge Check if the issue is fixed in the update.

**Comment by Samadhan-Medge** [comment] 2017-01-06 13:35
@Livin21 Its working perfect. Thanks :+1:

**Comment by Samadhan-Medge** [comment] 2017-01-12 06:35
@Livin21 DroidAwesome.setFontFileName(""); Not working

**Comment by Livin21** [comment] 2017-01-13 05:06
@Samadhan-Medge You mean empty string("") as input not working?

**Comment by Samadhan-Medge** [comment] 2017-01-13 05:42
@Livin21 No I'm passing font name as parameter like `DroidAwesome.setFontFileName("my-font.ttf");` but its not working for me. I also tried put same line in the class which extends Application.

**Comment by Livin21** [comment] 2017-01-17 05:05
@Samadhan-Medge Check the new release. No need to add file to assets now. But this method affects rendering in android studio. This is due to restrictions in android studio rendering sandbox.

**Closed as completed by Livin21** 2017-01-17 05:05 UTC

**Comment by Samadhan-Medge** [comment] 2017-01-17 06:03
@Livin21 As this new release has a limitation to use the font icons defined in `FontAwesome` class i.e `font_awesome.ttf`. As we are defining our own font file icons and need to set my own font file. Rest other thing are fine.
